name: Hello world action
on: [push]
jobs:
  hello_world_job: # job id
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Hello world action step
        uses: ./
        id: hello
        with:
          who-to-greet: "Kelvin E Mjuni"
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time}}"

